version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: twitter-db
    ports:
      - "27017:27017"
    hostname: mongo
  spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twitter-app
    hostname: spring
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      SPRING_APPLICATION_JSON: '{
                "spring.data.mongodb.uri" : "mongodb://mongo:27017/twitter_db"
              }'
    restart: always